name: Build Native Discord RPC (.so)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native-libs:
    name: Build .so files for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Install required tools
        run: sudo apt-get update && sudo apt-get install -y zip make

      - name: Make build.sh executable
        run: chmod +x ndk/build.sh

      - name: Run native build script
        run: ./ndk/build.sh

      - name: Prepare .so zip
        run: |
          mkdir -p dist
          cp -r lib/android dist/
          cd dist
          zip -r native-libs.zip android
          mv native-libs.zip ../

      - name: Upload .so artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-libs
          path: native-libs.zip
